name: nyc_airbnb_dev4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.0.1
  - ipython
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core
  - matplotlib
  - pandas
  - git
  - pip
  - pip:
      - wandb==0.13.9
