name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - requests=2.26.0
  - pip=22.3.1
  - hydra-core=1.3.1
  - pip:
      - wandb==0.13.9
      - hydra-joblib-launcher==1.2.0
      - setuptools==66.1.1
      - protobuf==3.19.0
      - omegaconf==2.2
      - mlflow==2.1.1
      - git+https://github.com/Qiuyi-Primrose-Chen/build-ml-pipeline-for-short-term-rental-prices-homework.git#egg=wandb-utils&subdirectory=components

